"""
Report generator - assembles analysis results into markdown.
"""

from datetime import datetime
from pathlib import Path

from jinja2 import Template

from src.utils.logger import setup_logger

logger = setup_logger("reporter")


# jinja2 template for the report
REPORT_TEMPLATE = """# {{ company }} — AI-Powered Company Analysis Report

> **Generated:** {{ timestamp }}
> **Model:** {{ model }}
> **Data Sources:** {{ sources | join(', ') }}
> **Analysis Modules:** {{ modules | length }}

---

## Executive Summary

{{ executive_summary }}

---

{% for module_name, content in sections.items() %}
## {{ module_name | replace('_', ' ') | title }}

{{ content }}

---

{% endfor %}

## Analysis Metadata

| Metric | Value |
|--------|-------|
| API Calls | {{ usage.api_calls }} |
| Total Tokens | {{ usage.total_tokens | default('N/A') }} |
| Prompt Tokens | {{ usage.prompt_tokens | default('N/A') }} |
| Completion Tokens | {{ usage.completion_tokens | default('N/A') }} |
| Estimated Cost | ${{ usage.estimated_cost_usd | default('N/A') }} |
| Model | {{ usage.model | default('N/A') }} |
| Report Generated | {{ timestamp }} |

---

*This report was generated by the AI Company Analysis Research Framework.
Data was collected from public sources and analyzed using LLM-powered
modules. This is not financial advice.*
"""


class ReportGenerator:
    """Generates markdown reports from analysis results."""

    def __init__(self, config: dict | None = None):
        self.config = config or {}
        self.output_dir = Path(self.config.get("output_dir", "output"))
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.report_format = self.config.get("format", "markdown")

    def generate(
        self,
        company: str,
        analysis_results: dict[str, str],
        usage_stats: dict,
        sources: list[str] | None = None,
    ) -> str:
        """Generate report and save to file. Returns filepath."""
        logger.info(f"Generating report: {company}")

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        executive_summary = analysis_results.pop(
            "executive_summary", "Executive summary not available.",
        )

        template = Template(REPORT_TEMPLATE)
        content = template.render(
            company=company,
            timestamp=timestamp,
            model=usage_stats.get("model", "N/A"),
            sources=sources or ["Yahoo Finance", "Google News"],
            modules=analysis_results,
            executive_summary=executive_summary,
            sections=analysis_results,
            usage=usage_stats,
        )

        # 파일명에 타임스탬프 붙여서 저장
        safe_name = company.replace(" ", "_").replace("/", "_")
        filename = f"{safe_name}_analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        filepath = self.output_dir / filename

        filepath.write_text(content, encoding="utf-8")
        logger.info(f"Saved: {filepath}")

        if self.report_format == "both":
            self._save_json(
                company, analysis_results, executive_summary,
                usage_stats, sources, timestamp
            )

        return str(filepath)

    def _save_json(
        self, company, sections, executive_summary,
        usage_stats, sources, timestamp,
    ) -> str:
        """Also save as JSON for programmatic use."""
        import json

        data = {
            "company": company,
            "timestamp": timestamp,
            "executive_summary": executive_summary,
            "analysis": sections,
            "usage": usage_stats,
            "sources": sources or [],
        }

        safe_name = company.replace(" ", "_").replace("/", "_")
        filename = f"{safe_name}_analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        filepath = self.output_dir / filename

        filepath.write_text(
            json.dumps(data, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        logger.info(f"JSON saved: {filepath}")
        return str(filepath)
